
// Objective-C API for talking to the following Go packages
//
//	github.com/TOIM/TOIM-sdk-core/v3/TOIM_sdk
//	github.com/TOIM/TOIM-sdk-core/v3/TOIM_sdk_callback
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TOIM_FRAMEWORK_H__
#define __TOIM_FRAMEWORK_H__

#include "TOIM_sdk.objc.h"
#include "TOIM_sdk_callback.objc.h"
#include "Universe.objc.h"

#endif
