workflows:
  openim-ios-demo-build:
    environment:
      xcode: latest  # 用官方推荐的Xcode环境，不额外改
    scripts:
      # 1. 进入官方Demo的Example目录（克隆后仓库名就是openim-ios-demo）
      - script: cd openim-ios-demo/Example
      # 2. 官方步骤：pod install，失败就更新repo（和官方文档完全一致）
      - script: pod install || pod repo update
      # 3. 官方步骤：编译运行（命令和Xcode打开xcworkspace编译完全等效）
      - script: |
          xcodebuild \
            -workspace OpenIMSDKUIKit.xcworkspace \  # 官方的xcworkspace文件名
            -scheme OpenIMSDKUIKit_Example \         # 官方默认的Scheme名（没改代码就不用动）
            -configuration Debug \                   # 官方开发测试用Debug，不是Release
            -sdk iphoneos \                          # 编译iOS设备版本
            clean build                               # 编译（和Xcode点“运行”一样）
    # 不需要产物就删artifacts，需要就保留（官方没提，可选）
    artifacts:
      - openim-ios-demo/Example/build/**/*.app  # 编译出的APP文件（官方Demo默认产物）
