workflows:
  openim-ios-demo-build:
    environment:
      xcode: latest  # 官方默认Xcode环境
    scripts:
      # 1. 正确进入Example目录（克隆后仓库名是openim-ios-demo，里面才有Example）
      - script: cd openim-ios-demo/Example  # 修正路径，和官方clone步骤完全对应
      # 2. 官方步骤：安装依赖
      - script: pod install || pod repo update
      # 3. 明确指定工作区和Scheme（和官方Demo的文件名完全一致，没有省略）
      - script: |
          xcodebuild \
            -workspace OpenIMSDKUIKit.xcworkspace \  # 明确指定官方的xcworkspace
            -scheme OpenIMSDKUIKit_Example \         # 明确指定官方默认Scheme
            -configuration Debug \
            -sdk iphoneos \
            clean build
    artifacts:
      - openim-ios-demo/Example/build/**/*.app  # 正确的产物路径
